title: Cairn
permalink: pretty
remote_theme: pmarsceill/just-the-docs
url: https://cairnrpg.com
logo: "/img/logo.png"
color_scheme: light
plugins:
  - jekyll-redirect-from

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "licensed under [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
